# Load package dependencies ----------------------------------------------------

library(targets)
library(tarchetypes)
library(here)
library(rmarkdown)
library(knitr)
library(kableExtra)
library(dplyr)
library(tidyr)
library(openxlsx)
library(ggplot2)
library(quarto)
library(Microsoft365R)
library(robotoolbox)
library(httr2)
